### ISSUE TITLE
Why not follow a MVC pattern?

### ISSUE THREAD

**Issue by boussou** [joefallon/kisstest#1]
Hi, this is a very good start.
I am a lover of the YAGNI principle, thus still afraid of the huge testing framework out there.

phpunit = 118 files + 12070 cloc (without composer dependancies !!!!)
Atoum = 276 files + 25621 cloc
simpletest 24 11554 cloc
**kisstest = 13 files / 1459 cloc** 

what is the next step?
I think you pick features from simpletest.
And keep it small!

**Comment by joefallon** [comment]
Thank you for the comments. Yes, I should have followed an MVC pattern. The testing framework is fairly old. I built the initial version in sometime in 2006. It needs to be updated a bit. 

I am not certain which features to add. Do you have any ideas?

**Comment by boussou** [comment]
just to clarify, cloc=sloc= line of codes

first, I think you need to update the exemple project and reorganize files. At first it was quite confusion.

Then, IMHO, try to implement same things as the laravel framework: integration with mockery & with a fake browser
- add more asserts

I could not tell until I tried it in a real project, but generally speaking anything that would allow us to avoid phpunit would be great.

**Comment by joefallon** [comment]
Mockery is extremely slow because of the extensive reflection it makes use of. The mocking support that I created is ridiculously fast and extremely easy to understand. 

If you would like to see some additional asserts, I would be happy to get a PR. 

The fact that it doesn't use MVC is completely hidden from users. Therefore, converting KissTest to use MVC is a currently a low priority.

Originally, the goals of the project were:
- Fast. Very, very fast.
- Easy to understand. New devs must be able to understand everything in no more than 10 minutes or so. 
- PHP configuration only. No XML. This also allows new devs to get a handle on everything super quickly.
- Execution environment must be the same as production (i.e. no command line requirements). This allows KissTest to be used on any computer with zero additional system configuration (besides basic PHP support). People often don't realize that the CLI execution environment for PHP is quite different from the Apache or FPM PHP execution environment.
- Beautiful output formatting. The output must be stunning, extremely useful, simple to understand, and user friendly. 

Since its' inception, I've added optional code coverage support. 

Most very experienced developers that have looked into Laravel closely disagree with a significant number of its' design and architectural decisions. I am no different.
